# Link auf die Datenbank. Diese Angabe ist sp√§ter anzupassen f√ºr die DBs der Projekte (Ausdruck hinter dem Slash)
spring.datasource.url=jdbc:postgresql://dumbo.inf.h-brs.de/demouser

# Username und Password. Diese Angaben sind durch die Projekte anzupassen. Daten bei Hr. Alda per E-Mail anfordern!
spring.datasource.username=demouser
spring.datasource.password=demouser

# Name des Treibers f√ºr das DBMS PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Angaben zur Aktualisierung des DB-Schemas. Sollte erst mal auf 'none' stehen, weitere Parameter m√∂glich
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none

# KIConnect API Key und Endpunkt f¸r den KI-Chatbot
kiconnect.api.key=<API-Key einf¸gen>
kiconnect.api.url=<Endpunkt einf¸gen>