# Link auf die Datenbank. Diese Angabe ist spÃ¤ter anzupassen fÃ¼r die DBs der Projekte (Ausdruck hinter dem Slash)
spring.datasource.url=jdbc:postgresql://dumbo.inf.h-brs.de/demouser

# Username und Password. Diese Angaben sind durch die Projekte anzupassen. Daten bei Hr. Alda per E-Mail anfordern!
spring.datasource.username=demouser
spring.datasource.password=demouser

# Name des Treibers fÃ¼r das DBMS PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Angaben zur Aktualisierung des DB-Schemas. Sollte erst mal auf 'none' stehen, weitere Parameter mÃ¶glich
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none

# Mögliche Werte für spring.jpa.hibernate.ddl-auto
# none ? nichts tun
# validate ? Schema prüfen
# update ? Schema aktualisieren (Achtung: neuer DB-Name eintragen!) - zu empfehlen
# create ? Schema neu erzeugen (Achtung: neuer DB-Name eintragen!)
# create-drop ? beim Start erzeugen und beim Stop löschen (Achtung: neuer DB-Name eintragen!)

# Mögliche Werte für spring.jpa.generate-ddl
# false -> Keine automatische Generierung des Datenbankschemas
# true -> JPA darf Tabellen, Spalten usw. anhand deiner Entity-Klassen generieren (weitere Konfiguration dann über
# den Parameter: spring.jpa.hibernate.ddl-auto